module.exports = [
  {
    filename: 'saturn-hula-hooping.gif',
    user: 'Gal Shir',
    title: 'Saturn Hula Hooping',
    url: 'https://dribbble.com/shots/4252236-Saturn-Hula-Hooping',
    backgroundColor: '#38216B',
    theme: 'light',
  },
  {
    filename: 'designing-for-humans.jpg',
    user: 'maryanne',
    title: 'Designing for humans in a digital world',
    url: 'https://dribbble.com/shots/3665326-Designing-for-humans-in-a-digital-world',
    backgroundColor: '#FFF2E9',
    theme: 'dark',
  },
  {
    filename: 'cosmic-sneak-peek.png',
    user: 'Radostina Georgieva',
    title: 'Cosmic Sneak Peek',
    url: 'https://dribbble.com/shots/4249027-Cosmic-Sneak-Peek',
    backgroundColor: '#DEE8F4',
    theme: 'dark',
  },
  {
    filename: 'connected-to-nature.png',
    user: 'Julia',
    title: 'Feeling connected to nature',
    url: 'https://dribbble.com/shots/3905987-Feeling-connected-to-nature',
    backgroundColor: '#fff',
    theme: 'dark',
  },
  {
    filename: 'taxi-driver.gif',
    user: 'Aslan A.',
    title: 'MyTaxi Driver',
    url: 'https://dribbble.com/shots/4015806-MyTaxi-Driver',
    backgroundColor: '#FECC02',
    theme: 'dark',
  },
  {
    filename: 'wednesday.gif',
    user: 'Jonas Mosesson',
    title: 'Wednesday',
    url: 'https://dribbble.com/shots/3050083-Wednesday',
    backgroundColor: '#F5F4E1',
    theme: 'dark',
  },
  {
    filename: 'proposal-girl.jpg',
    user: 'Katiuska Pino',
    title: 'Girl',
    url: 'https://dribbble.com/shots/4828188-Girl',
    backgroundColor: '#E35899',
    theme: 'light',
  },
  {
    filename: 'fridaybeers.gif',
    user: 'Animade',
    title: 'Friday Beers',
    url: 'https://dribbble.com/shots/4794274-Friday-Beers',
    backgroundColor: '#406DEB',
    theme: 'light',
  },
  {
    filename: 'pigeon.gif',
    user: 'EJ Hassenfratz',
    title: 'Carrier Pigeon',
    url: 'https://dribbble.com/shots/4833060-Carrier-Pigeon',
    backgroundColor: '#75D999',
    theme: 'light',
  },
  {
    filename: 'crayon.jpg',
    user: 'Joseph Chernashki',
    title: 'Crayon pattern',
    url: 'https://dribbble.com/shots/4882170-Crayon-pattern',
    backgroundColor: '#FFFBEF',
    theme: 'dark',
  }
]
